### ISSUE TITLE
Push current releases to maven central

### ISSUE THREAD

**Issue by ChristianCiach** [openhab/jamod#17]
Hi! Thank you for maintaining this library!

I see that the current version on GitHub is 1.3.4.OH, but on Maven Central the latest published version seems to be 1.2.3.OH: https://mvnrepository.com/artifact/org.openhab.osgiify/net.wimpi.jamod/1.2.3.OH

Could you publish the current release to Maven Central?

**Comment by ssalonen** [comment]
That kind of OSGified artifact is no longer maintained. Instead, this jamod fork is compiled in modbus transport bundle, see openhab-core repo: https://github.com/openhab/openhab-core/tree/main/bundles/org.openhab.core.io.transport.modbus

The org.openhab.osgiify/net.wimpi.jamod:1.2.3.OH was probably deployed by openhab/openhab-osgiify ([link to old revision](https://github.com/openhab/openhab-osgiify/tree/8f9701fd0c179c86c875304767cf2182eb2082cc/net.wimpi.jamod)) originally.

Having said that, the jar from this repo is deployed to normal openhab repos: https://openhab.jfrog.io/ui/repos/tree/General/libs-release%2Fnet%2Fwimpi%2Fjamod%2F1.3.4.OH

**Comment by ChristianCiach** [comment]
I see! So the correct artifact to use seems to be https://mvnrepository.com/artifact/net.wimpi/jamod/1.3.4.OH (which redirects to your Jfrog repo). Thanks!

**Comment by ssalonen** [comment]
@ChristianCiach 

Please also note that this fork is very passively maintained, and mainly to fix critical bugs for openHAB. In case you are looking for more general purpose modbus java library, that is more well maintained, I would advice to have a look at https://github.com/steveohara/j2mod

**Comment by ChristianCiach** [comment]
That's solid advice. Thanks again!

**Comment by kaikreuzer** [comment]
@ssalonen Should we clarify this in https://github.com/openhab/jamod/blob/main/README.md or even archive this repo?

**Comment by ssalonen** [comment]
Sounds like a good idea to clarify this in README. 

Personally I think it does not make sense to use this fork outside openHAB context...there are better alternatives for that.

In fact, ideally openHAB would switch to maintained fork but we seem to enter the topic of fragmented serial port implementations in java (e.g. Steveohara fork using jserialcomm which is incompatible with openHAB to my understanding). Do you see a way around this?

I think archiving is wrong thing to do if it makes the repo read only?

**Comment by kaikreuzer** [comment]
> Do you see a way around this?

No, not really.

> I think archiving is wrong thing to do if it makes the repo read only?

That's correct. We would have to revive it everytime we want to do a change - indeed not the right thing to do.

Could you come up with a PR for the README then?
